#ifndef TRAVELLINGSALESMANPROBLEMBRUTEFORCE_PROBLEMSOLVER_H
#define TRAVELLINGSALESMANPROBLEMBRUTEFORCE_PROBLEMSOLVER_H


class ProblemSolver {

};


#endif //TRAVELLINGSALESMANPROBLEMBRUTEFORCE_PROBLEMSOLVER_H
